import Head from 'next/head'
import axios from 'axios'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import Navigation from '../../components/navigation'
import { Wrapper } from './index'
import { Header,Message } from './products/[productId]'


export const Button = styled.button`
padding: 10px 20px;
width:100%;
background-color: var(--black-color);
font-size:1em;
font-family:'Quicksand';
font-weight:600;
color:var(--white-color);
border-radius:1rem;
border:1px solid var(--black-color);
margin:0.5rem 0;
&:hover {
  background-color:var(--yellow-color);
  border:1px solid var(--yellow-color);
  transition: 0.5s ease;
  color:var(--black-color);
}
cursor:pointer;
`


const Label = styled.label`
font-size:0.75rem;
color:var(--gray-color);
font-family:'Heebo';
margin-top:0.25rem;

`

const Column = styled.div`
display: flex;
flex-direction: column;
align-items: flex-start;
justify-content: flex-start;
width: 100%;
margin: 3em 0em;
`

const Input = styled.input`
width: 10em;
padding: 0.5rem;
border: 1px solid #666;
width:50vw;
border:none;
border-radius:1rem;
outline:1px solid var(--black-color);
margin: 0.25rem 0;
&:focus {
  outline:1px dashed var(--yellow-color);
  transition:0.3s ease;
}
`

const Form = styled.form`
display: flex;
flex-direction: column;
justify-content: flex-start;
align-items: flex-start;
`

export default function AddProduct() {
  const router = useRouter()
  const [product, setProduct] = useState('')
  const [price, setPrice] = useState('')
  const [color, setColor] = useState('')
  const [brand, setBrand] = useState('')
  const [description, setDescription] = useState('')
  const [material, setMaterial] = useState('')

  const [image, setImage] = useState('');



  const [response, setResponse] = useState(null);
  const [error, setError] = useState(false);
  const [success, setSuccess] = useState(false)
  const [errorMessage, setErrorMessage] = useState('Please enter valid information')
  const [successMessage, setSuccessMessage] = useState('Product Added Successfully')

  const handleKeyPress = event => {
    // Allow a dot only if the input value does not already contain a dot
    const inputValue = event.target.value;
    if (event.key === '.' && inputValue.includes('.')) {
      event.preventDefault();
    }
  };


  const handlePrice = event => {
    const inputValue = event.target.value;
    // Prevent non-numeric characters from being entered
    if (/^\d*\.?\d*$/.test(inputValue)) {
      setPrice(parseFloat(inputValue));
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();


    // if (response.status === 401) {
    //   // Display the error message to the user
    //   setErrorMessage('Not authenticated')
    // } else {
    // }

    if (
      product.length <= 0 ||
      price.length <= 0 ||
      color.length <= 0 ||
      brand.length <= 0 ||
      description.length <= 0 ||
      material.length <= 0 ||
      image.length <= 0
    ) {
      setErrorMessage("Please enter valid information");
      setError(true);
      setSuccess(false);
      return; // stop the function from proceeding
    }

    try {
      const parsedprice = Math.floor(parseFloat(price) * 100)
      const { data } = await axios.post('/api/products/products', {
        product,
        price: parsedprice,
        color,
        brand,
        description,
        material,
        image
      });
      setResponse(data);
      setError(null);
      setSuccess(true);
      setProduct('');
      setPrice('');
      setColor('');
      setBrand('');
      setDescription('');
      setMaterial('');
      setImage(null);
      console.log(data)
    }
    catch (error) {
      setResponse(error.response.data);
      setError(true);
      if (error.response.status === 401) {
        setErrorMessage('Not Authenticated')
      } else {}
      console.log(error.response.data)
      setResponse(null);
      setSuccess(false);
    }


  };

  useEffect(() => {
    if (response) {
      setTimeout(() => {

      router.push('/products')
      }, 1200);

    }
  }, [response]);
  
  

  return (
    <>
      <Head>
          <title>Add Product</title>
          <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700&family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Wrapper style={{flexDirection:'column'}}>
        <Navigation />

        {error ? <Message>{errorMessage}</Message> : ''}
        {success ? <Message>{successMessage}</Message> : ''}

        <Header>Upload a Product</Header>

        <Form onSubmit={handleSubmit}>
          <Label for='product'>PRODUCT</Label>
          <Input type="text" value={product} onChange={(e) => setProduct(e.target.value)} placeholder='...apple headphones' />
          <Label for='product'>PRICE</Label>
          <Input type="number" value={price} onChange={handlePrice} onKeyPress={handleKeyPress} placeholder='...$249.99'  />
          <Label for='product'>COLOR</Label>
          <Input type="text" value={color} onChange={(e) => setColor(e.target.value)} placeholder='...white' />
          <Label for='product'>BRAND</Label>
          <Input type="text" value={brand} onChange={(e) => setBrand(e.target.value)} placeholder='...Apple' />
          <Label for='product'>DESCRIPTION</Label>
          <Input maxlength="1000" type="text" value={description} onChange={(e) => setDescription(e.target.value)} placeholder='...Apple AirPods are wireless Bluetooth earbuds designed specifically to work with your iPhone and iPad.'  />
          <Label for='product'>MATERIAL</Label>
          <Input type="text" value={material} onChange={(e) => setMaterial(e.target.value)} placeholder='...plastic' />
          <Label for='product'>IMAGE</Label>
          <Input type="text" value={image} onChange={(e) => setImage(e.target.value)} placeholder='...https://www.apple.com/v/airpods/og/images/og__d9z2xq2q2y2a.png?202010211712' />
          <Button type="submit">Add Product</Button>
        </Form>
      </Wrapper>
    </>
  )
}