import { useSession, signIn, signOut } from "next-auth/react"
// import { unstable_getServerSession } from "next-auth/next"
// import {authOptions} from './api/auth/[...nextauth]'
import styled from "styled-components"
import { useRouter } from 'next/router'
import Head from "next/head"
import { Button } from "./addProduct"
import { Player } from '@lottiefiles/react-lottie-player';

export const Image = styled.img`
width:30%;
height:30%;
border-radius:50%;
border:2px solid black;
background-color:white;
padding:3rem;
background-color:var(--yellow-color);
`


export const Wrapper = styled.div`
display:flex;
padding: 3rem 10rem 3rem 10rem;
align-items:center;
justify-content:flex-start;
width:100vw;
min-height:100vh;
background-color: var(--white-color);
`

export const Row = styled.div`
display:flex;
flex-direction:row;
`

export const Column = styled.div`
display:flex;
flex-direction:column;
align-items:center;

`

export const Email = styled.div`
color:var(--gray-color);
font-size:0.75rem;
`

export const User = styled.div`
text-align:center;
margin-top:1rem;
font-family:'Quicksand';
font-size:1.5rem;
`

export const UserProfile = styled.div`
margin-bottom:3rem;
display:flex;
flex-direction:column;
align-items:center;
justify-content:center;
`

const Logo = styled.div`
font-family:'Quicksand';
font-size:3rem;
font-weight:600;
color:var(--black-color);
`

export default function Profile() {
  const { data: session } = useSession()
  const router = useRouter()
    return (
      <>
      <Head>
        <title>Review Hive</title>
        <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@100;200;300;400;500;600;700;800;900&family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Wrapper style={{height:'100vh', width:'100vw', gap:'5rem', alignItems:'center', justifyContent:'center'}}>

        { session ? <Column>
        <Logo style={{marginBottom:'2rem'}}>ReviewHIVE</Logo>
        <UserProfile>
          <Image src={session.user.image}/>
          <User>{session.user.name}</User>
          <Email>{session.user.email}</Email>
        </UserProfile>

        <Button onClick={() => signOut()}>Sign out</Button>
        <Button onClick={() => router.push('/products')} > Enter Hive </Button>

        </Column> :
        
        <Row style={{justifyContent:'center', alignItems:'center'}}>

        <Column style={{justifyContent:'center',}}>
        <Logo>ReviewHIVE</Logo> 
        <Button onClick={() => signIn()} style={{marginTop:'2rem'}}>Sign in with Github</Button>
        </Column>
        <Player 
        autoplay
        loop
        src='animations/bee.json'
        style={{height: '300px', width: '300px'}}
        />

        </Row> }



      </Wrapper>
      </>
    )
    }
  
  // } else 
  // return (
  //   <>
  //     Not signed in <br />
  //     <button onClick={() => signIn()}>Sign in</button>
  //   </>
  // )


// export async function getServerSideProps(context) {
//     const session = await unstable_getServerSession(context.req, context.res, authOptions)

//     if (!session) {
//         return {
//             redirect: {
//                 destination: "/api/auth/signin",
//                 permanent: false,
//             },
//         }
//     }
    
//     return {
//         props: { session },
//     }
// }